#include "Managers/HudManager.h"
#include "superclasses/Player.h"
#include <algorithm>

ActorPlayer::ActorPlayer(const char *filepath) : Entity(filepath) {
	held = false;
	heldFrames = 0;
	chargeLevel = 0;
	// ensure parity with sprite

	SDL_Log("-==Loading Sub Actor==-");

	m_sprite->Draw_Src(0, 0, 16, 16); // TODO: refactor actorplayer to be base class instead nad purge the player class (it does literally nothing) so i can then build up the othercharacter classes and whatever
	m_sprite->Draw_Dst(320.0f / 2.0f, 240.0f / 2.0f);
	m_sprite->Draw_Siz(16.0f, 16.0f);
	m_gamepad = nullptr;

	// SDL_Log("[ACTORPLAYER] successful instantiation");
}

ActorPlayer::ActorPlayer() : Entity("assets/img/Polar_Star_Players.bmp") {
	SDL_Log("Loaded Actor: ActorPlayer");

	m_sprite->Draw_Src(0, 0, 16, 16); // TODO: refactor actorplayer to be base class instead nad purge the player class (it does literally nothing) so i can then build up the othercharacter classes and whatever
	m_sprite->Draw_Dst(320.0f / 2.0f, 240.0f / 2.0f);
	m_sprite->Draw_Siz(16.0f, 16.0f);
	m_gamepad = nullptr;
}

void ActorPlayer::Update(double dt) {
	const bool *state = SDL_GetKeyboardState(nullptr);
	inputs(state, dt);
	collision(state);
}

void ActorPlayer::Render() {
	if (m_sprite->get_Y() < GameDefs::WindowHeight * .1f) {
		Hud::getInstance().makeTranslucent();
	} // bounds for when player is hidden behind UI elements

	if (m_sprite->get_Y() > GameDefs::WindowHeight * 0.1f) {
		Hud::getInstance().makeOpaque();
	}

	// m_sprite->m_dst = m_sprite->m_dst; // moved // REDUNDANT???
	m_sprite->Render();
}

void ActorPlayer::move(float x, float y) {
	m_sprite->Draw_Dst(x, y); // just a wrapper for player movement
}

void ActorPlayer::inputs(const bool *state, double dt) { //implementation of holding is passed on to each indiviudal weapon for them to figure it out, this inputs function simply maintains the minimum possible required information to give the weapons to deal with
	if (held) {						 // check if we held on previous frame
		if (state[SDL_SCANCODE_X]) { // if still holding increment hold frames by 1
			heldFrames += 1; //add check to stop counting frames when I hit some NOT arbitrary limit I'll decide later on
			// arsenal[weaponIDX]->Hold(); //pass in frametime, we'll figure out a solution for charged weapon VFX later
			//we could also just not do that 
			// we dont really need whatever 's below we can just pass in the held frametime into the function once it's complete

			// SDL_Log("Held for %d frames", heldFrames);
			// if (heldFrames >= 340) {
			// 	// SDL_Log("Level MAX CHARGED");
			// 	chargeLevel = 3;
			// } else if (heldFrames > 160) {
			// 	// SDL_Log("Level 3 CHARGED");
			// 	chargeLevel = 2;
			// } else if (heldFrames > 40) { // TODO: imaginary frame counts generated by machine : review this later
			// 	// SDL_Log("Level 2 CHARGED");
			// 	chargeLevel = 1;
			// }
		} else { // otherwise reset held state
			SDL_Log("INPUT RELEASED");
			//fire corresponding shot
			// SDL_Log("FIRED %d at LEVEL %d", weaponIDX, chargeLevel);
			//reset weapon state
			held = false;
			heldFrames = 0;
			chargeLevel = 0;
		}
	} else if (state[SDL_SCANCODE_X]) { // continue if we werent holding an input over from previous frame
		held = true;
		heldFrames += 1;
		SDL_Log("INPUT PRESSED");
		arsenal[weaponIDX]->Shoot();
		// press shoot -> check gun equipped -> derive bullet type from that -> spawn bullet (add to queue)
	}

	movement(state, dt);
}

void ActorPlayer::movement(const bool *state, double dt) {
	if (GameDefs::joystick != NULL) {
		int total, i;
		total = SDL_GetNumJoystickHats(GameDefs::joystick);
		for (i = 0; i < total; i++) {
			const Uint8 hat = SDL_GetJoystickHat(GameDefs::joystick, i);

			if (hat & SDL_HAT_RIGHT || state[SDL_SCANCODE_RIGHT]) {
				m_sprite->Offset_X(static_cast<float>(GameDefs::PlayerSpeed * dt));
			}
			if (hat & SDL_HAT_LEFT || state[SDL_SCANCODE_LEFT]) {
				m_sprite->Offset_X(-static_cast<float>(GameDefs::PlayerSpeed * dt));
			}
			if (hat & SDL_HAT_DOWN || state[SDL_SCANCODE_DOWN]) {
				m_sprite->Offset_Y(static_cast<float>(GameDefs::PlayerSpeed * dt));
			}
			if (hat & SDL_HAT_UP || state[SDL_SCANCODE_UP]) {
				m_sprite->Offset_Y(-static_cast<float>(GameDefs::PlayerSpeed * dt));
			}
		}
	} else if (GameDefs::joystick == NULL) {
		if (state[SDL_SCANCODE_RIGHT] || state[SDL_SCANCODE_D]) {
			m_sprite->Offset_X(static_cast<float>(GameDefs::PlayerSpeed * dt));
			// SDL_Log("[ACTORPLAYER] Input received");
		}
		if (state[SDL_SCANCODE_LEFT] || state[SDL_SCANCODE_A]) {
			m_sprite->Offset_X(-static_cast<float>(GameDefs::PlayerSpeed * dt));
			// SDL_Log("[ACTORPLAYER] Input received");
		}
		if (state[SDL_SCANCODE_DOWN] || state[SDL_SCANCODE_S]) {
			m_sprite->Offset_Y(static_cast<float>(GameDefs::PlayerSpeed * dt));
			// SDL_Log("[ACTORPLAYER] Input received");
		}
		if (state[SDL_SCANCODE_UP] || state[SDL_SCANCODE_W]) {
			m_sprite->Offset_Y(-static_cast<float>(GameDefs::PlayerSpeed * dt));
			// SDL_Log("[ACTORPLAYER] Input received");
		}
	}
}

void ActorPlayer::collision(const bool *state) {
	if (m_sprite->get_Y() > GameDefs::WindowHeight - m_sprite->get_W()) m_sprite->Draw_Y(GameDefs::WindowHeight - m_sprite->get_H());
	if (m_sprite->get_X() > GameDefs::WindowWidth - m_sprite->get_W()) m_sprite->Draw_X(GameDefs::WindowWidth - m_sprite->get_W());
	if (m_sprite->get_Y() < 0.0f) m_sprite->Draw_Y(0.0f);
	if (m_sprite->get_X() < 0.0f) m_sprite->Draw_X(0.0f);
}

void ActorPlayer::swapWeaponLeft(const bool *state) {
	// pick new weapon in left direction
	// pass new weapon & trigger weapon switch animation in gui handler
}

void ActorPlayer::swapWeaponRight(const bool *state) {
}

void ActorPlayer::shoot(const bool *state) {
}